def categorize(x):
    if x in sources.keys():
        return sources[x]
    return 'Misc'

# All categories that have been defined
cat = ['Clothing', 'Food & Drink', 'Entertainment', 'Gas', 'School', 'Work', 'Donations', 
       'Gifts', 'Health & Hygiene', 'Housing & Rent', 'Cell', 'Investments']

# Expenses or income that is determined by source
sources = {
    "Aldo Shoes" : 'Clothing',
    "Sears" : 'Clothing',
    "American Eagle" : 'Clothing',
    "Shoppers Drug Mart" : 'Health & Hygiene',
    "Aeropostale" : 'Clothing',
    "Starbucks" : 'Food & Drink',
    "HMV" : 'Entertainment',
    "McDonalds" : 'Food & Drink',
    "H&M" : 'Clothing',
    "Forever 21" : 'Clothing',
    "Urban Planet" : 'Clothing',
    "Chapters" : 'Entertainment',
    "Cineplex" : 'Entertainment',
    "Wonderland" : 'Entertainment',
    "Yorkland" : 'Work',
    "Camp Ke-Mon-Oya" : 'Work',
    "Compassion Canada" : 'Donations',
    "Metro" : 'Food & Drink',
    "The Body Shop" : 'Health & Hygiene',
    "Fairweather" : 'Clothing',
    "NTCS" : 'Work',
    "SilverCity" : 'Entertainment',
    "PizzaPizza" : 'Food & Drink',
    "World Vision" : 'Donations',
    "Apple" : 'Entertainment',
    "Cora's" : 'Food & Drink',
    "On the Go" : 'Food & Drink',
    "Food Basics" : 'Food & Drink',
    "No Frills" : 'Food & Drink',
    "The Bay" : 'Clothing',
    "Tim Hortons" : 'Food & Drink',
    "Canada Helps" : 'Donations',
    "Toys R Us" : 'Entertainment',
    "Cosmo Music" : 'Entertainment',
    "Winners" : 'Clothing',
    "St. John's Music" : 'Entertainment',
    "Magicuts" : 'Health & Hygiene',
    "Value Village" : 'Clothing',
    "Menchie's" : 'Food & Drink',
    "Laura Petite" : 'Clothing',
    "Stitches" : 'Clothing',
    "Bootlegger" : 'Clothing',
    "Michel's Baguette" : 'Food & Drink',
    "Payless Shoes" : 'Clothing',
    "M&Ms" : 'Food & Drink',
    "Virgin Mobile" : 'Cell',
    "Bowlerama" : 'Entertainment',
    "Canada Computers" : 'Entertainment',
    "University of Waterloo" : 'School',
    "Brubakers Cafeteria" : 'Food & Drink',
    "Sobeys" : 'Food & Drink',
    "Seoul Soul" : 'Food & Drink',
    "Waterloo Water" : 'Housing & Rent',
    "Union Gas" : 'Housing & Rent',
    "Waterloo North Hydro" : 'Housing & Rent',
    "Waterloo Café" : 'Food & Drink',
    "Sheridan College" : 'Work',
    "Williams" : 'Food & Drink',
    "University Bookstore" : 'School',
    "Geo Semiconductor" : 'Work',
    "UW Browsers Café" : 'Food & Drink',
    "ISARA Corporation" : 'Work',
    "EIT Cafe" : 'Food & Drink',
    "Canadian Solar" : 'Work',
    "Joe Fresh" : 'Clothing',
    "Canada" : 'Tax & Government'
};

# Expenses or income that is determined by item
items = {
    "Gift" : 'Gifts',
    "Investment" : 'Investments',
    "Ticket" : 'Entertainment',
    "Babysitting" : 'Work',
    "Tutoring" : 'Work',
    "Sponsorships" : 'Donations',
    "Operation Christmas Child" : 'Donations',
    "Peace Tree" : 'Donations',
    "Food Drive" : 'Donations',
    "Shoeboxes" : 'Donations',
    "Camp" : 'Work',
    "Website" : 'Work',
    "Education" : 'School',
    "Clothing" : 'Clothing',
    "Shopping" : 'Clothing',
    "Scholarship" : 'Education',
    "Donation" : 'Donations',
    "University" : 'Education',
    "Rent" : 'Housing & Rent',
    "Utilities" : 'Housing & Rent',
    "Tuition" : 'Education',
    "For" : 'Gifts', # Slightly risky...
    "Visa" : 'Credit Card',
    "Internet" : 'Housing & Rent',
    "Birthday" : 'Gifts',
    "Concert" : 'Entertainment',
    "Water" : 'Housing & Rent',
    "Hydro" : 'Housing & Rent',
    "Gas" : 'Housing & Rent'
};